### ISSUE TITLE
Custom index

### ISSUE THREAD

**Issue by alexander-myltsev** [Sqooba/scala-timeseries-lib#2]
Hi, 

would you merge the PR on custom index (see [that](https://github.com/carldata/timeseries/issues/127)) if I make it?

Also, what's the license of the lib?

**Comment by Shastick** [comment]
Hello, and thanks for your interest in this library.

If I understand you correctly, by _custom_ you mean a typed index? Ie, you would want to have a generic trait `TimeSeries[K,V]` where `K` is the type of the key, instead of using `Long` for everything?

If so, it would be worth putting some thought into this (we do have something like that on the back of our heads, but for now we're perfectly happy with Long's everywhere).

**Comment by alexander-myltsev** [comment]
Yes, I need custom key type.

**Comment by Shastick** [comment]
Sounds like a fair request to me :) 

Some thoughts from the top of my head:
 - the key type needs to be comparable -> probably easy
 - wondering about non-primitive key types: what about the overhead? Can we deal with that problem with value types? 
 - could we retain the "type" of the key in some other manner while still using Longs internally? 

If you have thoughts on this we'd be pleased to read them. If you intend to write an implementation, we're also more than happy to look at some drafts before you do the whole thing.

Cheers

**Comment by Shastick** [comment]
Regarding the licence: we forgot to put it up. We'll soon add the Apache 2.0 licence.

**Comment by alexander-myltsev** [comment]
@Shastick thank you for the response, and sorry for my long reply.

I'm exploring the Dotty compiler. And made some work on time series at [my pet project](https://github.com/okama-io/cifrum-scala/tree/master/core/src/main/scala/io/okama/timeseries). Will be looking at your repo when you decide to switch to Dotty. Feel free to close the issue.
